name: "Podcast Generator"
author: "arturo zenteno"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using:"docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiters email addres
    required: true
    default: ${{ github.actor}}@localhost
  name:
    description: The commiters name
    required: true
    default: ${{ github.actor }}
